This directory defines modules to define the database populated by Aurora at BluePillar data and to access said database.

* Aurora Access

The authentication method for the Aurora servers is Security Assertion Markup Language (SAML) is an XML-based, open-standard data format used to exchange authentication and authorization data between parties using the Palo Alto Networks Global Protect protocol.

To access the network, send a =POST= command to read SAML content like =prelogin-cookie=, =slo=, and =auth-status= then invoke the proper network manager command from the output.

This database contains =filters= for =tags= of which we may read historical data.

* PostgreSQL Access

To gain access to the PostgreSQL server, one must =SSH= onto the server first, then log into the PostgreSQL program of choice. 

* Element Hierarchy

We may define the metering hierarchy by containment. The rule is as follows:

=Sites= *contains* =Buildings= which *contains* =Meters=.

This forms a [[https://en.wikipedia.org/wiki/Posetal_category][posetal category]], making the following query transactions trivial:

- How much power does the Quadrangle loop draw at a given point in time?

- What is the total demand per square foot of POST Building and the chiller plant?

- That is the time of the peak demand for Manoa?

- How close (in time) are the peaks of Manoa campus and the peaks of each building complex?

For each element of the hierarchy we establish a table in the =aurora_api= schema in PostgreSQL.
