#+TITLE: Forcasting
#+PROPERTY: header-args:python3 :exports "results" :session forcasting :pandoc t :async yes :results value

* Goals
One goals of the project is to understand building behavior.

Of course, *understand* and *building behavior* are very general terms and completely up to interpretation. However, those were the specifications I was told and any inquiries for further specification have been refused.

My self imposed definition takes the following form; build a predictive model, misbehavior is then a deviation from the predicted value.


* Method
The predictive model will be a Long Short-term Memory Recurrent Neural Network LSTM-RNN using TensorFlow and Keras.

Authors propose a Long Short Term Memory Networks based Encoder-Decoder scheme for Anomaly Detection (EncDec-AD) that learns to reconstruct 'normal' time-series behavior, and thereafter uses reconstruction error to detect anomalies.

The setup is as follows:
Suppose we have a time series \( X \)  of length \( L \)  where each point is an \( m \)-dimensional vector of readings at time \( t \). First, train the LSTM Encoder-Decoder model to reconstruct the time series. Reconstruction errors are used to obtain an anomaly score, where a higher score indicates a higher likelihood.


* References

The code takes inspiration from the following papers (available freely through [[https://manoa.hawaii.edu/library/][UH Library]]  or on [[https://arxiv.org/][Arxiv]]):

He, Y. L., Chen, L., Gao, Y., Ma, J. H., Xu, Y., & Zhu, Q. X. (2022). Novel double-layer bidirectional LSTM network with improved attention mechanism for predicting energy consumption. ISA transactions, 127, 350-360.

Lai, G., Chang, W. C., Yang, Y., & Liu, H. (2018, June). Modeling long-and short-term temporal patterns with deep neural networks. In The 41st international ACM SIGIR conference on research & development in information retrieval (pp. 95-104).

My deepest gratitude to Dr. Michael J. Roberts, Dr. Peter Sadowski, and the authors of the papers cited.
